version: '2.17'
services:
  Opsgo:
    image: 'cbs:latest'
    restart: always
    hostname: 'cbs'
    environment:
      TZ: Asia/Shanghai
    ports:
      - '8080:80'
    volumes:
      - 'config/manager.yaml:/root/.cbs/manager.yaml'
